---
- hosts: all
  become: true
  tasks:
  - name: Install Httpd and php and update repository
    package:
     name: 
     - "{{ apache_package }}"
     - "{{ php_package }}"
     - "{{ mysql_package }}"  
     state: present
     update_cache: yes
       
    
