---
- hosts: all
  become: true
  tasks:
  - name: Install Httpd and php and update repository
    yum:
     name: 
     - httpd
     - php
     update_cache: yes
     state: latest  
    when: ansible_distribution == "Amazon"
  - name: add php support for apache for ubuntu
    apt:
     name: libapache2-mod-php
     state: latest  
    when: ansible_distribution == "Ubuntu"
