---
- hosts: workstations
  become: true
  tasks:
  - name: Install updates Amazon linux
    tags: always
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Amazon"

- hosts: db_servers
  become: true
  roles:
  - db_servers

- hosts: file_servers
  become: true
  roles:
  - file_servers


- hosts: workstations
  become: true
  roles:
  - workstations


  











  
  
  

