
- name: Describe RDS Instance
  shell: aws --region="{{ alarm_conf.rds_alarms_region }}" rds describe-db-instances -db-instance-identifier alarm_conf.DBInstanceIdentifier
  register: rds_alarms_instance_details


- set_fact:
    memory_warning_threshold: "{{ (rds_alarms_instance_class[rds_alarms_instance_details.DBInstances.DBInstanceClass].memory | float) * 10000000 * (100 - alarm_config.warning_threshold ) }}"
  when: alarm_conf.metric == 'FreeableMemory' 

- set_fact:
    storage_warning_threshold: "{{ (rds_alarms_instance_details.DBInstances.AllocatedStorage | float) * 10000000 * (100 - alarm_config.warning_threshold ) }}"
  when: alarm_conf.metric == 'FreeStorageSpace' 



- name: Create RDS CPU Alarm
  include_tasks: "{{ playbook_dir }}/roles/aws-alarm-rds/tasks/_create_cpu_alarm.yml"
  vars:
    alarm_conf: "{{ alarm_config }}"
  when: alarm_config.metric == 'CPUUtilization'

- name: Create RDS MEMORY Alarm
  include_tasks: "{{ playbook_dir }}/roles/aws-alarm-rds/tasks/_create_memory_alarm.yml"
  vars:
    alarm_conf: "{{ alarm_config }}"
    memory_warning_threshold: "{{ memory_warning_threshold }}"
  when: alarm_config.metric == 'FreeableMemory'

- name: Create RDS STORAGE Alarm
  include_tasks: "{{ playbook_dir }}/roles/aws-alarm-rds/tasks/_create_storage_alarm.yml"
  vars:
    alarm_conf: "{{ alarm_config }}"
    storage_warning_threshold: "{{ storage_warning_threshold }}"
  when: alarm_config.metric == 'FreeStorageSpace'