- name: Create RDS alarm
  ec2_metric_alarm:
    state: "{{ alarm_conf.state | default('present') }}"
    region: "{{ alarm_conf.rds_alarms_region }}"
    name: "{{ alarm_conf.name }}"
    description: "{{ ' High '+  alarm_conf.metric+'( '+alarm_conf.warning_threshold+' )'  +' for ' + alarm_conf.DBInstanceIdentifier }}"
    metric: "{{ alarm_conf.metric }}"
    namespace: "AWS/RDS"
    statistic: "{{ alarm_conf.statistic | default(rds_default_statistic)}}"
    comparison: "{{ alarm_conf.comparison | default(rds_default_comparison) }}"
    threshold: "{{  alarm_conf.warning_threshold  }}"
    period: "{{ alarm_conf.period | default(rds_alarms_period) }}"
    evaluation_periods: "{{ rds_alarms_evaluation_periods }}"
    unit: "{{ alarm_conf.unit | default(rds_default_unit) }}"
    dimensions: {"DBInstanceIdentifier": "{{ alarm_conf.DBInstanceIdentifier }}"}
    alarm_actions: "{{ rds_alarms_common_action_list | union(alarm_conf.alarm_actions) }}"