---

- name: Create RDS Storage alarm
  ec2_metric_alarm:
    state: "{{ alarm_conf.state | default('present') }}"
    region: "{{ alarm_conf.rds_alarms_region }}"
    name: "{{ alarm_conf.name }}"
    description: "{{ 'Disk space for '+ alarm_conf.DBInstanceIdentifier+' Database '+ alarm_conf.warning_threshold |string +'% Used' }}"
    metric: "FreeStorageSpace"
    namespace: "AWS/RDS"
    statistic: "{{ alarm_conf.statistic | default(rds_default_statistic)}}"
    comparison: "<="
    threshold: "{{  storage_warning_threshold  }}"
    period: "{{ alarm_conf.period | default(rds_alarms_period) }}"
    evaluation_periods: "{{ rds_alarms_evaluation_periods }}"
    unit: "Bytes"
    dimensions: {"DBInstanceIdentifier": "{{ alarm_conf.DBInstanceIdentifier }}"}
    alarm_actions: "{{ alarm_conf.alarm_actions | default(rds_alarms_common_action_list) }}"