---
# tasks file for aws-alarm-rds

- name: Describe RDS Instance
  shell: aws --region="{{ rds_alarms_region }}" rds describe-db-instances
  register: rds_alarms_instance_details


- name: Create Alarm
  include_tasks: "{{ playbook_dir }}/roles/aws-alarm-/tasks/_ec2.yml"
  vars:
    rds_alarm_conf: "{{ item.value }}"
  loop: "{{ aws_alarm_rds| dict2items }}"