---
- name: "Install Nginx on EC2 machine"
  hosts: ec2-nginx
  become: true
  become_user: root
  gather_facts: true
  tasks:
    - name: "Install Nginx"
      package: name=nginx state=present
    - name: "Start Nginx"
      service:
        name: nginx
        state: started
