---
- name: "Install Nginx on EC2 machine"
  hosts: aws_ec2
  become: true
  become_user: root
  gather_facts: true
  tasks:
    - name: "install epel release"
      yum: name=epel-release
    - name: "Install Nginx"
      yum: name=nginx state=present
    - name: "Start Nginx"
      service:
        name: nginx
        state: started
