---

- name: Create RDS Memory alarm
  ec2_metric_alarm:
    state: "{{ alarm_conf.state | default('present') }}"
    region: "{{ Alarm_region }}"
    name: "{{ 'RDS-'+DatabaseIdentifier+'-'+alarm_conf.alarm_type+'-'+alarm_conf.warning_threshold|string+'%-Used' }}"
    description: "{{ 'Low Memory Available for '+ DatabaseIdentifier+' RDS Database '+ alarm_conf.warning_threshold |string +'% Used' }}"
    metric: "FreeableMemory"
    namespace: "AWS/RDS"
    statistic: "{{ rds_default_statistic }}"
    comparison: "<="
    threshold: "{{  memory_warning_threshold  }}"
    period: "{{ rds_alarms_period }}"
    evaluation_periods: "{{ rds_alarms_evaluation_periods }}"
    unit: "Bytes"
    dimensions: {"DBInstanceIdentifier": "{{ DatabaseIdentifier }}"}
    alarm_actions: "{{ alarm_conf.alarm_actions | default(rds_alarms_common_action_list) }}"